In [1]:
import pandas as pd

In [2]:
file1 = "../CSVs/FBRefDatabase2018-19.csv"
file2 = "../CSVs/FBRefDatabase2019-20.csv"
file3 = "../CSVs/FBRefDatabase2020-21.csv"
file4 = "../CSVs/FBRefDatabase2021-22.csv"
file5 = "../CSVs/FBRefDatabase2022-23.csv"
files = [file1, file2, file3, file4, file5]

In [3]:
df = pd.read_csv(file1)
df.head(5)

,Player Name,Position,Club Name,Age,Starts,Mins,Goals,npG,Assists,crdY,crdR,xG,npXG,xA,Year
0,Shkodran Mustafi,0,0,26,31,"2,611",2.0,2.0,0.0,9.0,0.0,1.5,1.5,0.6,0
1,Pierre-Emerick Aubameyang,2,0,29,30,"2,726",22.0,18.0,5.0,0.0,0.0,22.6,18.5,4.2,0
2,Granit Xhaka,1,0,25,29,"2,498",4.0,4.0,2.0,10.0,0.0,2.0,2.0,3.4,0
3,Alexandre Lacazette,2,0,27,27,"2,502",13.0,13.0,8.0,2.0,0.0,11.7,11.7,3.7,0
4,Sokratis Papastathopoulos,0,0,30,25,"2,198",1.0,1.0,2.0,12.0,0.0,0.8,0.8,0.7,0

# Add years to the dataframe

In [4]:
# This might break other code lol

# i = 0
# for file in files:
#     df = pd.read_csv(file)
#     df["Year"] = i
#     df.to_csv(file, index=False, na_rep='Unknown')
#     i += 1

# The algorithm the combine the data

In [5]:
# 1. Find a player P
# 2. Find their club C, and the year Y
# 3. Get all of the stats of the Starting 11 for C in the year (Y - 1)
#     You should now have player P's stats in the year Y alongside the starting
#     11 for C in the year (Y - 1). Player P should be playing for C in the year
#     Y.
# 4. Organise that into 1 row in with a fixed length (NN has fixed input)
# 5. From here we can do other things (PCA, Removing rows w mcl, scalling etc)

# Notes:
# - Ideally we would choose all players on a team, but we have to choose a fixed 
# number of players because of the NNs fixed input size
# - If a player only exists in 1 year Y and not in another year Y-1, they will 
# have to be removed from the dataset.

# 0. Extra stuff

In [ ]:
# finding all clubs
                    # all_clubs = []

                    # for file in files:
                    #     df = pd.read_csv(file)
                    #     all_clubs += list(df["Club Name"])
                    #     # clubs_in_season = set(clubs_in_season)
                    #     # all_clubs.append(clubs_in_season)
                    #     # all_clubs.append(list(df["Club Name"]))

                    # # all_clubs = set(all_clubs)
                    # all_clubs = set(all_clubs)
                    # all_clubs
                    # # set(df["Club Name"])
# restricting positions
                    # df["Position"] = df["Position"].str[:2]

# 1. Find a player P 
# 2. Find their club C, and the year Y

In [7]:
# print(df.iloc[3])
print(df.iloc[3]["Player Name"])
print(df.iloc[3]["Position"])
print(df.iloc[3]["Club Name"])
print(df.iloc[3]["Year"])

name = df.iloc[3]["Player Name"]
pos  = df.iloc[3]["Position"]
club = df.iloc[3]["Club Name"]
year = df.iloc[3]["Year"]

Alexandre Lacazette
2
0
0

# 3. Get all of the stats of the Starting 11 for C in the year (Y - 1)

In [8]:
next_year = year + 1

In [9]:
# sorting by club and minutes
df.sort_values(by=["Mins"])
df.groupby("Club Name")

,Player Name,Position,Club Name,Age,Starts,Mins,Goals,npG,Assists,crdY,crdR,xG,npXG,xA,Year
0,Shkodran Mustafi,0,0,26,31,"2,611",2.0,2.0,0.0,9.0,0.0,1.5,1.5,0.6,0
1,Pierre-Emerick Aubameyang,2,0,29,30,"2,726",22.0,18.0,5.0,0.0,0.0,22.6,18.5,4.2,0
2,Granit Xhaka,1,0,25,29,"2,498",4.0,4.0,2.0,10.0,0.0,2.0,2.0,3.4,0
3,Alexandre Lacazette,2,0,27,27,"2,502",13.0,13.0,8.0,2.0,0.0,11.7,11.7,3.7,0
4,Sokratis Papastathopoulos,0,0,30,25,"2,198",1.0,1.0,2.0,12.0,0.0,0.8,0.8,0.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,Rúben Vinagre,0,26,19,7,710,0.0,0.0,0.0,1.0,0.0,0.5,0.5,0.8,0
466,Ivan Cavaleiro,2,26,24,6,693,3.0,3.0,1.0,1.0,0.0,2.2,2.2,1.5,0
467,Morgan Gibbs-White,1,26,18,5,663,0.0,0.0,1.0,1.0,0.0,1.1,1.1,1.3,0
468,Léo Bonatini,2,26,24,0,135,0.0,0.0,1.0,0.0,0.0,1.3,1.3,0.1,0
469,Max Kilman,0,26,21,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [22]:
# we have next_year, and the club name 
player_stats = list(df.loc[0][1:-1])
player_stats

[0, 0, 26, 31, '2,611', 2.0, 2.0, 0.0, 9.0, 0.0, 1.5, 1.5, 0.6]

In [35]:
team_df = df[df["Club Name"] == 0]
team_df

,Player Name,Position,Club Name,Age,Starts,Mins,Goals,npG,Assists,crdY,crdR,xG,npXG,xA,Year
0,Shkodran Mustafi,0,0,26,31,"2,611",2.0,2.0,0.0,9.0,0.0,1.5,1.5,0.6,0
1,Pierre-Emerick Aubameyang,2,0,29,30,"2,726",22.0,18.0,5.0,0.0,0.0,22.6,18.5,4.2,0
2,Granit Xhaka,1,0,25,29,"2,498",4.0,4.0,2.0,10.0,0.0,2.0,2.0,3.4,0
3,Alexandre Lacazette,2,0,27,27,"2,502",13.0,13.0,8.0,2.0,0.0,11.7,11.7,3.7,0
4,Sokratis Papastathopoulos,0,0,30,25,"2,198",1.0,1.0,2.0,12.0,0.0,0.8,0.8,0.7,0
5,Lucas Torreira,1,0,22,24,"2,382",2.0,2.0,2.0,7.0,1.0,1.5,1.5,1.2,0
6,Mattéo Guendouzi,1,0,19,23,"2,149",0.0,0.0,0.0,9.0,0.0,0.6,0.6,1.8,0
7,Alex Iwobi,2,0,22,22,"1,970",3.0,3.0,6.0,0.0,0.0,3.5,3.5,7.0,0
8,Sead Kolašinac,0,0,25,22,"1,887",0.0,0.0,5.0,5.0,0.0,0.4,0.4,6.0,0
9,Nacho Monreal,0,0,32,21,"1,861",1.0,1.0,3.0,5.0,0.0,1.3,1.3,1.7,0
10,Mesut Özil,1,0,29,20,"1,735",5.0,5.0,2.0,2.0,0.0,1.7,1.7,4.1,0
11,Henrikh Mkhitaryan,2,0,29,19,"1,641",6.0,6.0,4.0,1.0,0.0,5.0,5.0,6.2,0
12,Héctor Bellerín,0,0,23,18,"1,533",0.0,0.0,5.0,3.0,0.0,0.9,0.9,2.2,0
13,Aaron Ramsey,1,0,27,14,"1,331",4.0,4.0,6.0,0.0,0.0,3.4,3.4,2.0,0
14,Laurent Koscielny,0,0,32,13,"1,331",3.0,3.0,0.0,1.0,0.0,1.4,1.4,0.2,0
15,Ainsley Maitland-Niles,0,0,20,11,987,1.0,1.0,1.0,2.0,1.0,0.9,0.9,0.9,0
16,Stephan Lichtsteiner,0,0,34,10,938,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.1,0
17,Rob Holding,0,0,22,9,807,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.2,0
18,Mohamed Elneny,1,0,26,5,380,0.0,0.0,0.0,0.0,0.0,0.4,0.4,0.2,0
19,Konstantinos Mavropanos,0,0,20,3,148,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.3,0
20,Carl Jenkinson,0,0,26,2,166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
21,Danny Welbeck,2,0,27,1,153,1.0,1.0,1.0,0.0,0.0,0.8,0.8,0.3,0
22,Joe Willock,1,0,18,1,64,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0
23,Denis Suárez,1,0,24,0,71,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
24,Eddie Nketiah,1,0,19,0,67,1.0,1.0,0.0,0.0,0.0,0.2,0.2,0.1,0
25,Bukayo Saka,2,0,16,0,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [51]:
stats_as_list = []
for i in range(min(15,len(team_df))):
    stats_as_list += list(team_df.loc[i][1:-1])

stats_as_list

[0,
 0,
 26,
 31,
 '2,611',
 2.0,
 2.0,
 0.0,
 9.0,
 0.0,
 1.5,
 1.5,
 0.6,
 2,
 0,
 29,
 30,
 '2,726',
 22.0,
 18.0,
 5.0,
 0.0,
 0.0,
 22.6,
 18.5,
 4.2,
 1,
 0,
 25,
 29,
 '2,498',
 4.0,
 4.0,
 2.0,
 10.0,
 0.0,
 2.0,
 2.0,
 3.4,
 2,
 0,
 27,
 27,
 '2,502',
 13.0,
 13.0,
 8.0,
 2.0,
 0.0,
 11.7,
 11.7,
 3.7,
 0,
 0,
 30,
 25,
 '2,198',
 1.0,
 1.0,
 2.0,
 12.0,
 0.0,
 0.8,
 0.8,
 0.7,
 1,
 0,
 22,
 24,
 '2,382',
 2.0,
 2.0,
 2.0,
 7.0,
 1.0,
 1.5,
 1.5,
 1.2,
 1,
 0,
 19,
 23,
 '2,149',
 0.0,
 0.0,
 0.0,
 9.0,
 0.0,
 0.6,
 0.6,
 1.8,
 2,
 0,
 22,
 22,
 '1,970',
 3.0,
 3.0,
 6.0,
 0.0,
 0.0,
 3.5,
 3.5,
 7.0,
 0,
 0,
 25,
 22,
 '1,887',
 0.0,
 0.0,
 5.0,
 5.0,
 0.0,
 0.4,
 0.4,
 6.0,
 0,
 0,
 32,
 21,
 '1,861',
 1.0,
 1.0,
 3.0,
 5.0,
 0.0,
 1.3,
 1.3,
 1.7,
 1,
 0,
 29,
 20,
 '1,735',
 5.0,
 5.0,
 2.0,
 2.0,
 0.0,
 1.7,
 1.7,
 4.1,
 2,
 0,
 29,
 19,
 '1,641',
 6.0,
 6.0,
 4.0,
 1.0,
 0.0,
 5.0,
 5.0,
 6.2,
 0,
 0,
 23,
 18,
 '1,533',
 0.0,
 0.0,
 5.0,
 3.0,
 0.0,
 0.9,
 0.9,
 2.2,
 1,
 0,
 27,
 14,
 '1,331',
 4.0,
 4.0,
 6.0,
 0.0,
 0.0,
 3.4,
 3.4,
 2.0,
 0,
 0,
 32,
 13,
 '1,331',
 3.0,
 3.0,
 0.0,
 1.0,
 0.0,
 1.4,
 1.4,
 0.2]

In [ ]:
# You should now have player P's stats in the year Y alongside the starting
# 11 for C in the year (Y - 1). Player P should be playing for C in the year Y.

In [ ]:
# 4. Organise that into 1 row in with a fixed length (NN has fixed input)
# 5. From here we can do other things (PCA, Removing rows w mcl, scalling etc)

# Notes:
# - Ideally we would choose all players on a team, but we have to choose a fixed 
# number of players because of the NNs fixed input size
# - If a player only exists in 1 year Y and not in another year Y-1, they will 
# have to be removed from the dataset.